CREATE DATABASE VERIFICENTRO;

USE VERIFICENTRO;

CREATE TABLE CLIENTE
(
	CLI_CVE_CLIENTE 	INT		NOT NULL	PRIMARY KEY AUTO_INCREMENT,
	CLI_NOMBRE		VARCHAR(30)	NOT NULL,
	CLI_APELLIDO_PATERNO	VARCHAR(20)	NOT NULL,
	CLI_APELLIDO_MATERNO	VARCHAR(20)	NULL,
	CLI_CORREO_ELECTRONICO	VARCHAR(45)	NOT NULL,
	CLI_TELEFONO		VARCHAR(20)	NOT NULL
);
CREATE TABLE AUTOMOVIL
(
	AUT_CVE_AUTOMOVIL	INT		NOT NULL	PRIMARY KEY AUTO_INCREMENT,	
	AUT_PLACA		VARCHAR(7)	NOT NULL,
	AUT_MODELO		VARCHAR(20)	NOT NULL,
	AUT_MARCA		VARCHAR(20)	NOT NULL,
	AUT_NUMERO_SERIE	VARCHAR(15)	NOT NULL,
	AUT_SERIE_MOTOR		VARCHAR(15)	NOT NULL,
    AUT_IMAGEN			VARCHAR(100)NOT NULL,
	AUT_TIPO_COMBUSTIBLE	INT		NOT NULL,

	CLI_CVE_CLIENTE 	INT		NOT NULL,
	FOREIGN KEY (CLI_CVE_CLIENTE) REFERENCES CLIENTE(CLI_CVE_CLIENTE)
);
CREATE TABLE CENTRO_VERIFICACION
(
	CEN_CVE_CENTRO		INT			NOT NULL	PRIMARY KEY AUTO_INCREMENT,
    CEN_RAZON_SOCIAL	VARCHAR(60)	NOT NULL,
    CEN_CALLE			VARCHAR(40)	NOT NULL,
    CEN_NUMERO			VARCHAR(10)	NOT NULL,
    CEN_COLONIA			VARCHAR(40)	NOT NULL,
    CEN_CODIGO_POSTAL	VARCHAR(5)	NOT NULL,
    CEN_MUNICIPIO		VARCHAR(25)	NOT NULL,
    CEN_ESTADO			VARCHAR(25)	NOT NULL
);
CREATE TABLE VERIFICACION
(
	VER_FECHA			DATE		NOT NULL,
    VER_ENCARGADO		VARCHAR(80)	NOT NULL,
    VER_DIAGNOSTICO		VARCHAR(200)NOT NULL,
    VER_COSTO			REAL		NOT NULL,
    VER_MONTO_MULTA		REAL		NOT NULL,
    
    CEN_CVE_CENTRO		INT			NOT NULL,
    AUT_CVE_AUTOMOVIL		INT			NOT NULL,
	
    FOREIGN KEY (CEN_CVE_CENTRO) REFERENCES CENTRO_VERIFICACION(CEN_CVE_CENTRO),
    FOREIGN KEY (AUT_CVE_AUTOMOVIL) REFERENCES AUTOMOVIL(AUT_CVE_AUTOMOVIL)
);
select * from cliente;

INSERT INTO CLIENTE VALUES(NULL, 'ANA', 'RUIZ', 'CORTES', 'acortes@hotmail.com', '7713456789');
INSERT INTO CLIENTE VALUES(NULL, 'LUIS', 'ANGEL', 'GRESS', 'langel@hotmail.com', '7718981234');
INSERT INTO CLIENTE VALUES(NULL, 'ROBERTO', 'AYUSO', 'ILLADES', 'eayuso@hotmail.com', '7711234567');

INSERT INTO AUTOMOVIL VALUES(NULL,'HXH3161','SONIC 2018','CHEVROLET','ERDS323F','SDFS32S','imagenes/clasico.jpg',1,1);
INSERT INTO AUTOMOVIL VALUES(NULL,'HGH2954','IONIC 2018','HYUNDAI','ER8T8T','IWE23IWEK','imagenes/car2.jpg',2,2);
INSERT INTO AUTOMOVIL VALUES(NULL,'XWH2334','ACCENT 2018','HYUNDAI','HF99F9F','8YUU56','imagenes/Car3.jpg',2,3);
INSERT INTO AUTOMOVIL VALUES(NULL,'HGH8922','ELANTRA 2018','HYUNDAI','WEFID89','GRTYRTR','imagenes/car4.jpg',1,1);
INSERT INTO AUTOMOVIL VALUES(NULL,'HXH4455','A3 2018','AUDI','VDKSDLK3','98UKJGH','imagenes/Ford-GT.jpg',1,2);

SELECT * FROM AUTOMOVIL;

UPDATE AUTOMOVIL SET AUT_IMAGEN = 'imagenes/clasico.jpg' WHERE AUT_CVE_AUTOMOVIL=1;
UPDATE AUTOMOVIL SET AUT_IMAGEN = 'imagenes/car2.jpg' WHERE AUT_CVE_AUTOMOVIL=4;
UPDATE AUTOMOVIL SET AUT_IMAGEN = 'imagenes/Car3.jpg' WHERE AUT_CVE_AUTOMOVIL=5;
UPDATE AUTOMOVIL SET AUT_IMAGEN = 'imagenes/car4.jpg' WHERE AUT_CVE_AUTOMOVIL=6;
UPDATE AUTOMOVIL SET AUT_IMAGEN = 'imagenes/Ford-GT.jpg' WHERE AUT_CVE_AUTOMOVIL=7;

